# Generated by Django 2.2.5 on 2021-08-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.CharField(default='None', max_length=60),
        ),
    ]
